### ISSUE TITLE
standalone.py crashed by SIGPIPE

### ISSUE THREAD

**Issue by futatuki** [viewvc/viewvc#157]
ViewVC Version: master, commit 569c4ce67de4ffb86565fe47f37204d55446dd11
OS: FreeBSD/amd64 11.1
Python Version: 2.7.15
http client: Firefox 61.0.2 (on FreeBSD/amd64)

On above environment, standalone.py occationally crashes by double fault (exception in exception handler) with stack trace like below:
```
Traceback (most recent call last):
  File "/usr/local/viewvc/bin/standalone.py", line 583, in <module>
    main(sys.argv)
  File "/usr/local/viewvc/bin/standalone.py", line 578, in main
    serve(options.host, options.port, ready)
  File "/usr/local/viewvc/bin/standalone.py", line 416, in serve
    ViewVCHTTPServer(host, port, callback).serve_until_quit()
  File "/usr/local/viewvc/bin/standalone.py", line 350, in serve_until_quit
    self.handle_request()
  File "/usr/local/lib/python2.7/SocketServer.py", line 275, in handle_request
    self._handle_request_noblock()
  File "/usr/local/lib/python2.7/SocketServer.py", line 292, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 347, in handle_error
    print '-'*40
  File "/usr/local/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/usr/local/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
AttributeError: 'NoneType' object has no attribute 'sendall'
```

With overriding SocketServer.BaseServer.handle_error(), by adding ViewVCHTTPServer.handle_error()
like
```
--- standalone.py.orig       2018-08-25 10:14:40.770479000 +0900
+++ standalone.py       2018-09-26 16:01:55.109422000 +0900
@@ -361,6 +361,18 @@ class ViewVCHTTPServer(BaseHTTPServer.HT
     BaseHTTPServer.HTTPServer.server_bind(self)
 
 
+  def handle_error(self, request, client_address):
+    """Handle an error gracefully. use stderr instead of stdout
+    to avoid double fault.
+    """
+    print >>sys.stderr, '-'*40
+    print >>sys.stderr, 'Exception happened during processing of request from',
+    print >>sys.stderr, client_address
+    import traceback
+    traceback.print_exc()
+    print >>sys.stderr, '-'*40
+
+
```
the server can avoid crash and produce log to stderr like below.

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 25010)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/local/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/local/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/local/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```
(Note: if the patched server is killed by Keyboard interrupt, the server still cannot catch the exception
 in lower level)

I think it may be platform, environment specific and not exact problem of ViewVC but of BaseHTTPServer of Python 2.7, JFYI.

**Comment by futatuki** [comment]
> (Note: if the patched server is killed by Keyboard interrupt, the server still cannot catch the exception
in lower level)

This is caused by `print 'server stopped'` line in `serve()` in `standalone.py`, and only if `ViewVCHTTPRequestHandler.run_viewvc()` fail to restore sys.stdout. 
Traceback sample is here:
```
Traceback (most recent call last):
  File "/usr/local/viewvc/bin/standalone.py", line 595, in <module>
    main(sys.argv)
  File "/usr/local/viewvc/bin/standalone.py", line 590, in main
    serve(options.host, options.port, ready)
  File "/usr/local/viewvc/bin/standalone.py", line 431, in serve
    print 'server stopped'
  File "/usr/local/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/usr/local/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
AttributeError: 'NoneType' object has no attribute 'sendall'
```

**Comment by cmpilato** [comment]
@futatuki Thanks for the report and analysis.  Care to produce a pull request for this?

**Comment by futatuki** [comment]
Thank you for care it. Now, I've done it.
