### ISSUE TITLE
crash viewvc-standalone

### ISSUE THREAD

**Issue by peterdd** [viewvc/viewvc#196]
```
Traceback (most recent call last):
  File "/usr/bin/viewvc-standalone", line 879, in <module>
    main(sys.argv)
  File "/usr/bin/viewvc-standalone", line 874, in main
    serve(options.host, options.port, ready)
  File "/usr/bin/viewvc-standalone", line 421, in serve
    ViewVCHTTPServer(host, port, callback).serve_until_quit()
  File "/usr/bin/viewvc-standalone", line 356, in serve_until_quit
    self.handle_request()
  File "/usr/lib/python2.7/SocketServer.py", line 278, in handle_request
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 350, in handle_error
    print '-'*40
  File "/usr/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
AttributeError: 'NoneType' object has no attribute 'sendall'
```

viewvc version 1.1.26 debian package used within debian 10 'buster' vagrant image
viewvc-standalone --host=10.0.0.31 
startet as vagrant user

**Comment by futatuki** [comment]
This seems just same as the issue #157, which was fixed between 1.1.26 and 1.1.27.
