### ISSUE TITLE
Nearly every request throws an Exception in bin/standalone.py in master

### ISSUE THREAD

**Issue by futatuki** [viewvc/viewvc#214]
<snip>

> 7. Check http server interfaces other than bin/standalone.py

I'm getting some irritating errors with bin/standalone.py, too.  Nearly ever request throws an Exception:

```
----------------------------------------
Exception happened during processing of request from ('172.28.0.1', 51950)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib64/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.6/http/server.py", line 407, in handle_one_request
    self.wfile.flush() #actually send the response if not already done.
ValueError: I/O operation on closed file.
----------------------------------------
```

_Originally posted by @cmpilato in https://github.com/viewvc/viewvc/issues/138#issuecomment-605108182_

**Comment by futatuki** [comment]
I found that self.wfile.close() is called when io.TextIOWrapper instance create by get_writeready_serverfile().

With this patch, it seems to be able to stop this exception.

```
--- lib/viewvc.py.orig       2020-04-11 00:48:53.570487000 +0900
+++ lib/viewvc.py     2020-04-12 18:17:42.469510000 +0900
@@ -91,6 +91,12 @@ _URL_SAFE_CHARS = "/*~"
 def cmp(a, b):
   return (a > b) - (a < b)
 
+class TextIOWrapper_noclose(io.TextIOWrapper):
+  def close(self):
+    if not self.closed:
+      self.closed = True
+      self.flush()
+      self.detach()
 
 class Request:
   def __init__(self, server, cfg):
@@ -958,7 +964,8 @@ def get_writeready_server_file(request, 
     fp = request.server.file()
 
   if is_text:
-    fp = io.TextIOWrapper(fp, 'utf-8', 'surrogateescape', write_through=True)
+    fp = TextIOWrapper_noclose(fp, 'utf-8', 'surrogateescape',
+                               write_through=True)
 
   return fp
 
```

**Comment by futatuki** [comment]
As I can't find better solusion than the patch above, I make a pull request as #230.

**Comment by futatuki** [comment]
The PR #230 was merged.
