### ISSUE TITLE
What is missing for an initial ViewVC 1.3 release?

### ISSUE THREAD

**Issue by mdiers** [viewvc/viewvc#250]
I'd like to suggest moving forward with the release of ViewVC 1.3.

There is a growing demand for an official release of ViewVC that no longer requires Python 2.
I image that most users nowadays will want to use distribution packages for deploying ViewVC. For packaging, it would be beneficial to have proper pre-releases and, eventually, releases.
Personally, I am working on a SUSE RPM package of ViewVC 1.3. I am prepared to test the SVN personality extensively, and the CVS personality somewhat less so. So far, I have not seen any blocking issues using a daily snapshot with SVN.

What do people think? Is it time for a release candidate?

**Comment by cmpilato** [comment]
Hey, Michael!  Overall, ViewVC 1.3 is looking pretty good.  Right now, it seems the biggest showstopper for ViewVC 1.3 is the checkins database feature (issue #213).  Sadly, I suspect that's a non-trivial shortcoming.

**Comment by futatuki** [comment]
> Here is a list of issues that block release of 1.3.0 , although I belive #109 and #228 had been resolved.

During the conversation in the issue #109, I realize that #109 is not solved yet.

**Comment by mdiers** [comment]
> I want to know how the users think priority between a official release that support Python 3 and
> support for cvsdb. If many people want the former, we need to make a release soon, I think.

I strongly suggest focusing on Python 3 support. So yes, please release sooner than later.

**Comment by mdiers** [comment]
> All that to say this: If ViewVC 1.3 either ships without the checkins database feature else doesn't ship at all, then I think it's time to kiss the feature goodbye.

I concur. It's the practical and realistic thing to do, isn't it?

**Comment by matthys70** [comment]
What is the current status?

I tried to install under Ubuntu 22.04.1 LTS and not working.
I tried to check the Python binding part but get:
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from svn.core import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'svn.core'

Also check if there is any module with svn and there is:
>>> help('modules svn')
Here is a list of modules whose name or summary contains 'svn'.
If there are any, enter a module name to get more help.
svn
svn.admin - svnadmin calls for managing a repository.
svn.common
svn.common_base
svn.config
svn.constants
svn.exception
svn.local
svn.remote
svn.utility
pysvn
pysvn._pysvn
pysvn._pysvn_3_10

Not sure if this mean I'm missing this svn.core one ...

If I try to access the ViewVC webpage I get a blank traceback and only displays:
An Exception Has Occurred
Python Traceback

**Comment by futatuki** [comment]
> What is the current status?

It's still under development, but very slow progress due to lack of resources.  

> I tried to install under Ubuntu 22.04.1 LTS and not working.
> I tried to check the Python binding part but get:
> Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
>             from svn.core import *
>             Traceback (most recent call last):
>             File "", line 1, in
>             ModuleNotFoundError: No module named 'svn.core'
> 

You need to install [python3-subversion](https://packages.ubuntu.com/jammy/python3-subversion) package.

**Comment by matthys70** [comment]
I installed the python3-subversion package as it indeed was missing but sadly didn't had any effect. Still not working :-(

**Comment by futatuki** [comment]
@matthys70 I see, however it is somewhat off topic in this original issue.
Could you open a new issue for your problem?

**Comment by futatuki** [comment]
> > Here is a list of issues that block release of 1.3.0 , although I belive #109 and #228 had been resolved.
> 
> During the conversation in the issue #109, I realize that #109 is not solved yet.

PR #109 was closed.  PR #127 is a part of PR #213, and PR #228 has been accomplished well, I think.

So, the rest of the release blockers are #213 and #280.

**Comment by cmpilato** [comment]
> So, the rest of the release blockers are #213 and #280.

...and it's possible that #280 is already finished and that I simply forgot to close the issue.

**Comment by futatuki** [comment]
@matthys70 

> And what does this mean for this issue, is either of the mentioned number (213 and 280) related to this?

Those are PR number that block an initial ViewVC 1.3 release.   So, the answer of this issue is to close those issues.

They are not directly related to your problem.  If you still have trouble with installing ViewVC mentioned above,  please open an issue for it,  as I told you before.

**Comment by kberry** [comment]
I suppose this is not news to anyone, but since I didn't see it explicitly discussed in the various python3 issues, let me mention that the current subversion release, 1.14.2, requires python3 in its swig-pl bindings. At least, I get a syntax error with p2:
```
python2 -c "from svn import client"
...
File "/l/subversion1142/lib/svn-python/libsvn/client.py", line 146                
    def svn_client_version() -> "svn_version_t const *":                        
                             ^                                                  
SyntaxError: invalid syntax                              
```

Thus, the current viewvc release does not support the current subversion release.

I'm just an onlooker, but reading issue #213, I admit I don't see why a complex, new, non-required feature like a checkin database (whatever that is :) should hold up a release that anyone wanting to use current subversion needs. And issue #280 looks like it is already considered closed for an initial 1.3 release, at least.

**Comment by futatuki** [comment]
> I suppose this is not news to anyone, but since I didn't see it explicitly discussed in the various python3 issues, let me mention that the current subversion release, 1.14.2, requires python3 in its swig-pl bindings. 

No, Subversion 1.14.2 still supports Python 2.7,  although to use Subversion SWIG Python binding with Python 2,  you must rebuild configure scripts by using autogen.sh and rebuild SWIG Python bindings with them.  Please see [INSTALL](https://svn.apache.org/viewvc/subversion/tags/1.14.2/INSTALL?revision=1899517&view=markup#l509) and [subversion/bindings/swig/INSTALL](https://svn.apache.org/viewvc/subversion/tags/1.14.2/subversion/bindings/swig/INSTALL?revision=1899517&view=markup) in Subversion's source tree.

**Comment by GeekishPedant** [comment]
I think I can shed some light on @matthys70's post as the same happened to me.

As @futatuki replied, the python3-subversion package contains the bindings.  The problem is there is an existing Python svn package with a site-packages/svn module. You see that you can import svn, so you should have the bindings, right?  Wrong.  

The python3-subversion package included modules installed for me on an RHEL9 system at /usr/lib/pylib3.9/site-packages.  These two modules were libsvn and...wait for it...svn.  There exists two unique site-packages/svn modules!  Until you realize this, it's all very confusing if you already have an svn module installed.  The svn module we had must have been installed because, gee, it sounds like it might helpful and used somewhere.  A thorugh search of /usr and /etc found nothing using the svn 1.0.1 package.

The ViewVC INSTALL file reminds installers that the bindings (now identified as site-packages/svn/* and site-packages/libsvn/*) must be in your path.  After disposing of the previous svn module, I placed a copy of the svn and libsvn modules from python3-subversion into the site-packages directory for my Python 3.9 virtual environment and all was copacetic on that front.

I also could not use ViewVC because the web page would only display a page which was empty except for 
An Exception Has Occurred
Python Traceback

I set the Apache LogLevel to trace8; even at that extreme level not a single entry was made into the error_log.

No error was being identified because sys.exc_info was not reporting the error for get_exception_data() to use.

A few print statements later I had identified the cause of the problem.  I had modified viewvc.conf to mimic our ViewVC 1.1 version.  That included  "directory=dir_new.ezt".  In the earlier ViewVC, all the template files were directly under the templates directory.  However, in ViewVC 1.3, templates contains only two subdirectories: classic, and default, each with their own set of template files.  When ViewVC tried to read dir_new.ezt, it choked because templates/dir_new.ezt didn't exist.

I commented out the directory assignment, letting ViewVC go with its default.  And ViewVC 1.3.0-dev worked with Subversion 1.14.1!

I think the only actionable item here is an increase in error catching.

**Comment by matthys70** [comment]
Strange, I used the new viewvc.conf and only enabled the svn_roots setting.
I also checked and got the templates/dir_new.ezt files etc.
If I comment out this svn_roots in the viewvc (so disabled it) it got and empty viewvc loaded and no error message.

**Comment by GeekishPedant** [comment]
I apologize for being unclear. I think I was relying on context.

The directory=dir_new.ezt is the specific error I encountered. But a number of errors could occur which result in the empty Python Trace. The problem is the error not being logged somewhere. (The ViewVC 1.3.0 used was the overnight dated 20240318. So possibly this has already been addressed.)

In viewvc-1.3.0-dev/lib, I made a backup of viewvc.py.  Then I edited viewvc.py's main() function.  I changed

except Exception:
    view_error(server, cfg)

to

except Exception as exc:
    with open('/path/to/test.log', 'a') as logfile:
        logfile.write(f"\nException:\n{exc}\n\n")
    logfile.close()
    view_error(server, cfg)

With this in place, test.log had the very friendly

Exception:
[Errno 2] No such file or directory: '/viewvc-1.3.0-dev/templates/default/dir_new.ezt'

A grep for dir_new.ezt located where dir_new_ezt was being set and all the pieces fell into place ("yada, yada yada", "Bob's your uncle", etc.).

**Comment by futatuki** [comment]
@GeekishPedant  For the porpose of trouble shooting, you can use "`statcktrace = 1`" in section "[options]" in viewvc.conf.  Then you can get stack trace of the exception on your Web browser, like:
```
An Exception Has Occurred

Python Traceback

  File "/usr/local/viewvc/lib/viewvc.py", line 5561, in main
    request.run_viewvc()
  File "/usr/local/viewvc/lib/viewvc.py", line 459, in run_viewvc
    self.view_func(self)
  File "/usr/local/viewvc/lib/viewvc.py", line 2410, in view_roots
    generate_page(request, "roots", data)
  File "/usr/local/viewvc/lib/viewvc.py", line 1025, in generate_page
    template = get_view_template(request.cfg, view_name, request.language)
  File "/usr/local/viewvc/lib/viewvc.py", line 974, in get_view_template
    return ezt.Template(cfg.path(tname))
  File "/usr/local/viewvc/lib/ezt.py", line 313, in __init__
    self.parse_file(fname, base_format)
  File "/usr/local/viewvc/lib/ezt.py", line 318, in parse_file
    self.parse(_FileReader(fname), base_format)
  File "/usr/local/viewvc/lib/ezt.py", line 832, in __init__
    self.text = open(fname, "r").read()
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/viewvc/templates/default-/roots.ezt'
```

So I don't think it is a missing feature for the ViewVC 1.3 release.

**Comment by GeekishPedant** [comment]
I tried stacktrace and it was fantastic!  Thanks.

**Comment by matthys70** [comment]
I tried the "statcktrace = 1" as mentioned, and still the same issue:
ModuleNotFoundError: No module named 'svn.core'

**Comment by futatuki** [comment]
@matthys70 your problem is obiously out of the topic of this issue, and we had moved to the issue #306 for your problem. Could you please continue in issue #306 ?

My answer  to suggest using "stacktrace = 1" was an negative opinion against the opinion that an increase in error catching is a missing item for ViewVC 1.3 release.  It's not for your situation.

**Comment by mgilsonMT** [comment]
Is there any update on when ViewVC version 1.3.0 will be ready for release? What is left outstanding that is stopping the release of ViewVC 1.3.0?

Ubuntu version 20.04 LTS (Focal Fossa) is reaching end of standard support in May 2025. Attempting to update servers to Ubuntu 22.04 LTS (Jammy Jellyfish) or 24.04 LTS (Noble Numbat) when using python 3 as python 2.7 is no longer supported removes the ability to utilize ViewVC.

**Comment by futatuki** [comment]
The only issue blocking 1.3.0 release is issue #213 (not changed since [Dec 1, 2022](https://github.com/viewvc/viewvc/issues/250#issuecomment-1332515609)).

Unfortunately there is no active developer for the issue.  So there is no update for the issue since then (at least the code committed on this repository) .

**Comment by kberry** [comment]
Since there is no one to work on 213, may I suggest it would be reasonable to make a release with the bug unfixed. Maybe that will provoke someone who cares about the "checkin database" to work on it. Or they can keep using the old release. Or whatever.

Meanwhile, it seems like the latest release has been unusable on current systems for some years (due to Python's incompatibility madness), which seems like a much worse problem. So far as I've seen, as things stand, it's effectively necessary to run a random repo version of viewvc on current systems.

**Comment by futatuki** [comment]
My understanding is that if we would release 1.3.0 without fix of #213, we would remove the "checkin database" feature completely by removing all relatede code and documents except the description about the history from (at least) HEAD of master branch, and 1.3.0 tag.  And then if someone would want the feature again, they should add code for it again (either by reverting the removal or by writing new code).

The issue of Debian's (and perhaps also other Linux distributions') packages is independent from the release of ViewVC.  The issue is simply that there is no package maintainer who is interested in ViewVC and is willing to be responsible for the package.  I'm using FreeBSD and its ports collection has devel/viewvc-devel,  which uses snapshot of master branch, and I belive it is well maintained.

**Comment by kberry** [comment]
> My understanding is that if we would release 1.3.0 without fix of #213,
> we would remove the "checkin database" feature completely 

Well, of course you wouldn't have to actually remove the code. Whatever
the UI is for it could simply be disabled. Or it could be #ifdef'd out.
Or whatever.

Anyway, isn't a release without the "checkin database" feature (whatever
that is) better than the current state -- namely, those few of us who
are still using svn having to pull a random snapshot from development?
The last release is not installable on current systems because of the
Python problem.  (Or installing in a vm/chroot of a Python2 system, also
suboptimal.)

> that there is no package maintainer who is interested in ViewVC and is
> willing to be responsible for the package. 

Then who is the "we" above? From what I've seen in the bug reports, I
thought you were the upstream maintainer :), since you are the one
answering so many questions! (Thank you.)

Is there really no one from subversion.apache.org who cares about
viewvc? Since subversion itself is still actively maintained, I had
thought that they must also care about viewvc, since they go together so
closely.

Thanks,
Karl

**Comment by futatuki** [comment]
> Well, of course you wouldn't have to actually remove the code. Whatever
> the UI is for it could simply be disabled. Or it could be #ifdef'd out.
> Or whatever.

No, since we are using version control system, we would remove related code, sample config, description in documents except about history would be removed, at least HEAD of master branch, to avoid confusion.  Those "removed" things would be still in the repository(, or other branch isolated from master branch which is head of development).

> Anyway, isn't a release without the "checkin database" feature (whatever
> that is) better than the current state -- namely, those few of us who
> are still using svn having to pull a random snapshot from development?

Not random snapshot.  Even master branch, we try to keep stable.  We expect that users are using latest snapshot at the time pulled it (and ideally if they meet some trouble on using snapshot and the snapshot is not latest at that time , then they would try on latest snapshot before reporting the issue, but I know it is only an ideal).

For packages, maintainers of the ViewVC package of some OS distribution may choose that they update or does not update their package by their responsibility when the upstream branch (here) is updated.

> The last release is not installable on current systems because of the
> Python problem.  (Or installing in a vm/chroot of a Python2 system, also
> suboptimal.)

Note that there still exist systems that supports Python 2.7, and [ActiveState still support Python 2.7](https://github.com/activestate/cpython).  Perhaps what is blocking installation of ViewVC 1.2.x nowaday is rather extra procedure to build Python 2.7 bindings for Subversion 1.4.x ([see the comment above](https://github.com/viewvc/viewvc/issues/250#issuecomment-1528935516)), e.g. pkgsrc in NetBSD provides ViewVC 1.2.3 but does not provide py27-subversion.

>>  that there is no package maintainer who is interested in ViewVC and is
>>  willing to be responsible for the package.

> Then who is the "we" above? From what I've seen in the bug reports, I
> thought you were the upstream maintainer :), since you are the one
> answering so many questions! (Thank you.)

"The ViewCVS group" including collaborators(only me?) here.  At least I'm not actively interested in maintaining the package for ViewVC in Debian, Ubuntu, fedora, and other Linux distributions',  because I don't need them on my work both on private and on job.

> Is there really no one from subversion.apache.org who cares about
> viewvc? Since subversion itself is still actively maintained, I had
> thought that they must also care about viewvc, since they go together so
> closely.

From the commit log, since ViewVC 1.2.0 was released, there is no other ViewVC committer than @cmpilato and I in the Apache Subversion Project.  ViewVC is not a part of Apache Subversion and there also alternative solution for browsing files, history of the repository,  so the maintenance of the ViewVC code is completely out of the scope of the Subversion Project.  Members of both groups are fundamentally volunteers and the purpose of the participation, motivation may be different each other.

**Comment by cmpilato** [comment]
And, putting my coding where my mouth is ...  https://github.com/viewvc/viewvc/pull/372

**Comment by futatuki** [comment]
If there is no one to disagree with removing checkins(commits) db from the `master` branch within some reasonable term, I think it is a week or so, let's go ahead; merge PR #372, close issue #213 as "won't fix", and then release 1.3.0, and finally close this issue.

**Comment by ziesemer** [comment]
I'm just seeing this as part of the above tag to #213, which I was subscribed to.

FWIW, from my perspective, the checkin database is the most critical value offered by ViewVC, which is why I've introduced ViewVC into the environments I have.  This was more often in years past, but at least one of these implementations was less than a year ago as an organization was still dedicated to using SVN while they are continuing plans towards moving to Git (and likely a modern platform that they includes its own commit search capabilities, etc.).  This is also what led to the interim fixes that I contributed to in #351.  "Interim", because #213 originally proposed moving everything to utf8mb4 - but at least, #351 brought everything up to consistency with utf8.  I've yet to run across a use case where this is not sufficient.

I haven't been following the other activity since my last efforts here just over a year ago, and also with the discussion now scattered across multiple tickets - but I guess I'm not understanding what is currently broken with the checkin database?  With the changes from #351, the feature is actively and successfully being used to this day in an organization I help support - including some very large databases, large commits, and with frequent use of extended characters across fields.

I'm all for doing what is needed to keep a project supportable, including issuing current releases, etc. - including if that means removing the current checkin database support.  However, I'd be curious how many other users of ViewVC are in the same boat as what I'm seeing here - or maybe I'm in the very slim minority...

**Comment by futatuki** [comment]
As I wrote on https://github.com/viewvc/viewvc/issues/250#issuecomment-2993364603,  if someone want the checkins db feature along with master branch codebase, they can make another branch than master (and 1.3.x in the future),  starting with HEAD of master branch (or 1.3.x),  by reverting 655e72d948b4a3a1571fb3a9109045615a118244(except the change on tempates/default/error.ezt), 6b74ee9edb69ff9d7b51bc620ef08b3727f30e1c, and be7bd63afbe432fec2f0a8ff93149cc22587a425. (e.g.  https://github.com/futatuki/viewvc/commits/e.g.-feature-commits-db/ )

However to keep maintain the branch, there need some one takes care of it.

**Comment by futatuki** [comment]
> I'm just not understanding if or where the checkins db feature is broken in such a way that it should block a new release as-is?

We drop the feature because of the resource to maintain it.  If it were released as-is, we might recieve help requests for the feature from users of the release.  I don't believe that all users read documents which describe that the feature is unsupported.  Instead so  I suggest the way to use it, and then only users who can maintain by theirselves can use it.

**Comment by futatuki** [comment]
A1:  
1. Check the current status of the feature again, at least check the tools for the feature works in most case, both on CVS and Subversion repository.
2.  If the some tool, especially used for newly setup, don't work at all, fix it
3. Write documents about
- The restrictions, known issues of current codebase and schema
- How to migration from old schema. (It might be possible by ALTER TABLE or so (I didn't check) however if they contains non-ascii characters in the old table,  I recommend to rebuild them from scratch because of interpretation of non-ascii characters)
- Excuse for the current status for this feature.
- Excuse for the future change of the schema. To resolve known issues, we should mostly change the current schema. (but it might not occure :))

I think we've not had vitality to do 1. ...

**Comment by futatuki** [comment]
As the conclusion was reset, I reopened issue #213.
  
> 1. Check the current status of the feature again, at least check the tools for the feature works in most case, both on CVS and Subversion repository.
> 
> 2. If the some tool, especially used for newly setup, don't work at all, fix it

Please move to issue #213 for the resolution of those, if we would work for resolve them.

**Comment by futatuki** [comment]
Based on the discussion above, I moved my example branch to maintain commits db feature with 1.3.x codebase into project repo as `issue213-feature-commits-db` branch.

**Comment by cmpilato** [comment]
* Commits database has been restored with `utf8mb4` character sets.
* I'd like @futatuki to weigh in on where we sit regarding his comment at https://github.com/viewvc/viewvc/issues/213#issuecomment-881835101 (I read it as "we're good because we now demand versions of MySQL/MariaDB that use `DYNAMIC` row format by default", but I'll let him correct me.)
* The project -- I daresay, the entire ViewVC-using world -- would appreciate @ziesemer testing the latest `master` branch code to make sure it is something he'd be comfortable deploying for a customer. 😉

**Comment by futatuki** [comment]
Yeah, I already  did `%s/ENGINE=InnoDB/& ROW_FORMAT DYNAMIC/` to schema_2.sql, and I'm preparing MariaDB environment (not done yet) :-)

**Comment by futatuki** [comment]
>  Yeah, I already did %s/ENGINE=InnoDB/& ROW_FORMAT DYNAMIC/ to schema_2.sql, and I'm preparing MariaDB environment (not done yet) :-)

It works as expected.  committed.

**Comment by futatuki** [comment]
> I overlooked that the issue [#354](https://github.com/viewvc/viewvc/issues/354) is also a mile stone of 1.3.0.

@cmpilato can we postpone the issue #354 to a mile stone of 1.3.1, or resolve soon ?
I don't think it is a critical issue that affect many users.

**Comment by cmpilato** [comment]
> [@cmpilato](https://github.com/cmpilato) can we postpone the issue [#354](https://github.com/viewvc/viewvc/issues/354) to a mile stone of 1.3.1, or resolve soon ? I don't think it is a critical issue that affect many users.

Yeah, there's really no good answer there.  I spent some more time looking at that one last week, and I'm convinced that _maybe_ looooong ago that download_href went to `HEAD` in the abstract, but it would have been forever before the pathrev changes landed.  I've fixed the docs to stop _claiming_ that it points to `HEAD` (because it clearly doesn't), but my proposal of a "base_href" that can be amended with extra parameters is, I think, not attainable (because `allowed_views`, `default_view`, etc.).

I will punt the request into `*unscheduled*`.

**Comment by futatuki** [comment]
Now the last milestone for 1.3.0 is this one.

I wrote about the condition to includes commits database feature in 1.3.0 release:

> 1. Check the current status of the feature again, at least check the tools for the feature works in most case, both on CVS and Subversion repository.
> 2. If the some tool, especially used for newly setup, don't work at all, fix it
> 3. Write documents about
> 
> 
>     * The restrictions, known issues of current codebase and schema
> 
>     * How to migration from old schema. (It might be possible by ALTER TABLE or so (I didn't check) however if they contains non-ascii characters in the old table,  I recommend to rebuild them from scratch because of interpretation of non-ascii characters)
> 
>     * Excuse for the current status for this feature.
> 
>     * Excuse for the future change of the schema. To resolve known issues, we should mostly change the current schema. (but it might not occure :))

I think we've already done 1. and 2. 

For 3.:
* The requirement for the DMS settings is described.  I meant that the "known issues" is on a conparison against 1.2.x, 1.1.x, so if it is none, nothing to do with it.
* Migration how to is described in "upgrading howto".
* I thought the problem in current status of this feature was that it wasn't maintained well, but I think it is only that it isn't mature yet (by comparison to other functions).
* If we'll need "the feature change of the shema",  it is when we'd like to improve Subversion support or so, and it is on 1.4.0-dev or 2.x-dev, it never happens on 1.3.x branch. So now I don't think this is need.

Then,  what is missing for an initial ViewVC 1.3 release?

**Comment by cmpilato** [comment]
I was going to propose that we roll a 1.3.0-beta Real Soon Now(tm), something that perhaps might rekindle the interest of those who have maintained ViewVC distro packages in the past.

**Comment by futatuki** [comment]
Or do we release 1.3.x from master branch, until significant new feature will start to develop?

**Comment by cmpilato** [comment]
> Or do we release 1.3.x from master branch, until significant new feature will start to develop?

I started to make the 1.3.x branch today, but then I wondered the same ... would it just be easier to keep working on `master` until some breaking change needs to land?  (IIRC, we didn't really go through this with 1.2.x because we knew quite well that future changes were going to be breaking changes.)

But upon some more reflection, I think we should branch 1.3.x, if only so that nightly builds of `master` aren't interpreted to be part of the 1.3.x lineage.  I'll setup the branches now.

**Comment by Conrad-T-Pino** [comment]
Python 3.13 deprecated Common Gateway Interface (cgi) module in version 3.11 and dropped it in 3.13 version.
See https://docs.python.org/3.13/library/cgi.html which breaks [lib/sapi.py Line 20](https://github.com/viewvc/viewvc/blob/master/lib/sapi.py#L20)  at Debian 13 with Python 3.13.5 version.

**Comment by futatuki** [comment]
@Conrad-T-Pino thank you for the report.  I also could confirm that legacy-cgi module in PyPI uses module name 'cgi'  so that existing source code could run without modification.

So the issue of `cgi` module is  for "Required packages" section in INSTALL file only.

**Comment by futatuki** [comment]
Do we have some BETA or RC before Release ?  Or release "1.3.0 Release" after some soak period?   As I caused serious regression in standalne server,  the stablility of the code in master branch might not be considered enough....

**Comment by cmpilato** [comment]
> Do we have some BETA or RC before Release ? Or release "1.3.0 Release" after some soak period? As I caused serious regression in standalne server, the stablility of the code in master branch might not be considered enough....

I assumed we'd do the "beta" or "rc1" thing.  Now, I have about 99.94% confidence that people are going to show up _en masse_ to test those variants, but ... at least we can say we tried.

**Comment by futatuki** [comment]
I see.  As we don't have the test suite for it, then...

1. Let's tag so that we/they can make sure what revision(commit) is the target of test/check (and/or freeze code in master)
2. Make a list of what {have been|should be} tested/checked one bye one.

Should we make new issue for 2. ?

**Comment by cmpilato** [comment]
As of a few minutes ago, `master` now tracks the development of ViewVC `1.4.x`.  Where possible, we will continue to work primarily from this branch, with backports to a new `1.3.x` branch, which has been created.  Soon, I will roll a 1.3.0-alpha1 release.

In the meantime, we should be developing a verification matrix.  I've enabled the Wiki feature of the project and created https://github.com/viewvc/viewvc/wiki/ViewVC-1.3-Testing as a place for tracking our test plan and status.

**Comment by cmpilato** [comment]
I decided to call the release beta1 (instead of alpha1), but it published at https://github.com/viewvc/viewvc/releases/tag/1.3.0-beta1.

**Comment by cmpilato** [comment]
1.3.0 is being release today.  Closing this issue.

**Comment by kberry** [comment]
Yay! Congratulations!!

**Comment by TechnologyClassroom** [comment]
Thank you!
