### ISSUE TITLE
top-level svn/ gets "TypeError: cannot deepcopy this pattern object" with python 3.6

### ISSUE THREAD

**Issue by kberry** [viewvc/viewvc#326]
I installed the nightly build of viewvc-1.3.0-dev-20230429 on Alma Linux 8,
using Subversion 1.14.2, which I built from source.

The viewvc.cgi has a shebang line of #!/usr/bin/python3
which is set to Python 3.6 on this system. Visiting my top-level /svn/ url, http://new.tug.org/svn/, then results in
```
An Exception Has Occurred
Python Traceback

TypeError: cannot deepcopy this pattern object
```

The same url works with Python 3.9. For my own and any other testing, I set up urls http://new.tug.org/svnp36 (explicitly uses #!/usr/bin/python3.6, fails) and 
http://new.tug.org/svnp39 (explicitly uses #!/usr/bin/python3.9, works). These are Pythons as packaged for EL8.

Unfortunately, due to the well-known Python incompatibilities, I can't switch python3 to be 3.9 without causing a different set of problems (not with viewvc).

Manually changing the shebang works well enough, but this seems like something that would be good to make work with 3.6 (if possible) or warn about in the documentation (if not). If it's already in the doc, sorry, I failed to see it.

**Comment by futatuki** [comment]
Thanks for the report.  I could confirm it.

With  "`python3.6 bin/standalone.py`", here is a stacktrace:
[[[
```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35520)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib64/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "bin/standalone.py", line 152, in do_GET
    self.handle_request("GET")
  File "bin/standalone.py", line 161, in handle_request
    self.run_viewvc()
  File "bin/standalone.py", line 334, in run_viewvc
    ot_cfg = copy.deepcopy(cfg)
  File "/usr/lib64/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib64/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib64/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
TypeError: cannot deepcopy this pattern object
----------------------------------------
```
]]]

Strictly this is not same error as @kberry reported, but it seems its cause is same:
`copy.deepcopy()` cannot copy `config.Config` (which is defined in lib/config.py).

I don't want dropping Python 3.6 support positively,  so I'll take a look if I have enough time.

**Comment by futatuki** [comment]
It turned out that `configparser.ConfigParser` object on Python 3.6 cannot copy by using `copy.deepcopy()`.  At least it can copy on Python 3.7.16 and Python 3.9.15.
