### ISSUE TITLE
ViewVC - "ImportError: No module named _core"

### ISSUE THREAD

**Issue by samkhamk** [viewvc/viewvc#358]
After OS upgrade from RHEL 7.9 to RHEL 8.10, We are facing binding issue between svn and python packages. The error we received is "ImportError: No module named _core"

Complete error,
```
Traceback (most recent call last):
  File "/etc/httpd/viewvc/lib/viewvc.py", line 4855, in main
    request.run_viewvc()
  File "/etc/httpd/viewvc/lib/viewvc.py", line 233, in run_viewvc
    roottype, rootpath = locate_root(cfg, self.rootname)
  File "/etc/httpd/viewvc/lib/viewvc.py", line 4776, in locate_root
    path_in_parent = find_root_in_parents(cfg, rootname, 'svn')
  File "/etc/httpd/viewvc/lib/viewvc.py", line 4760, in find_root_in_parents
    rootpath = vclib.svn.find_root_in_parent(pp, rootname)
  File "/etc/httpd/viewvc/lib/vclib/svn/__init__.py", line 90, in find_root_in_parent
    return canonicalize_rootpath(rootpath)
  File "/etc/httpd/viewvc/lib/vclib/svn/__init__.py", line 39, in canonicalize_rootpath
    rootpath = _canonicalize_path(rootpath)
  File "/etc/httpd/viewvc/lib/vclib/svn/__init__.py", line 23, in _canonicalize_path
    import svn.core
  File "/usr/lib64/python2.7/site-packages/svn/core.py", line 26, in <module>
    from libsvn.core import *
  File "/usr/lib64/python2.7/site-packages/libsvn/core.py", line 17, in <module>
    _core = swig_import_helper()
  File "/usr/lib64/python2.7/site-packages/libsvn/core.py", line 16, in swig_import_helper
    return importlib.import_module('_core')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _core

```

Currently, we are running the following packages on the server:
```
OS:- RHEL 8.10
Perl:- v5.26.3
Subversion:- v1.10.2
HTTPD:-  v2.4.37
Python:- 2.7.18, Python3: 3.6.8
Viewvc :- 1.1.25
```

we just wanted to know how to get Viewvc back functional, not sure what bindings are required,

Can someone guide, 

Regards,
SAM

**Comment by futatuki** [comment]
If you want to get ViewVC work with Subversion repository,  it needs Subversion Python bindings built with Subversion libraries installed in your environment, in your case for Subversion 1.10.2 and Python 2.7.18.

As it seems you are using packages,  you need to search the Subversion Python bindings package in same package repository from which your Subversion package was installed.

**Comment by futatuki** [comment]
If you installed subversion package from RHEL 8's base or update repo,  suitable Python bindings package may not be provided. (c.f. [RHEL 8 release note](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html-single/8.0_release_notes/index)

In the case you need to search subversion and its bindings packages from other package repositories(see https://subversion.apache.org/packages.html#redhat),  or building Subversion and Python bindings from source file.

**Comment by samkhamk** [comment]
@futatuki 
Appreciate the time and support you had give, I am checking further with CIRATA (WANDISCO) . we can clos this issue
