### ISSUE TITLE
standalone.py throws exception when per-root configuration is used [Tigris #445]

### ISSUE THREAD

**Issue by cmpilato** [viewvc/viewvc#94]
## Description

```
Recipe
1. visit a ViewVC instance that's served by standalone.py.  See root listing.
2. visit one of the root.
3. re-visit the root listing.

You get this trackback:

Traceback (most recent call last):
  File "/usr/local/viewvc-1.1.3/lib/viewvc.py", line 4315, in main
    request.run_viewvc()
  File "/usr/local/viewvc-1.1.3/lib/viewvc.py", line 398, in run_viewvc
    self.view_func(self)
  File "/usr/local/viewvc-1.1.3/lib/viewvc.py", line 1838, in view_roots
    allroots = list_roots(request)
  File "/usr/local/viewvc-1.1.3/lib/viewvc.py", line 4170, in list_roots
    auth = setup_authorizer(cfg, request.username, root)
  File "/usr/local/viewvc-1.1.3/lib/viewvc.py", line 805, in setup_authorizer
    authorizer, params = cfg.get_authorizer_and_params_hack(rootname)
  File "/usr/local/viewvc-1.1.3/lib/config.py", line 314, in
get_authorizer_and_params_hack
    assert(self.root_options_overlayed == 0)
AssertionError

Core Problem:
ViewVC's core logic assumes that the configuration file is process per-request,
but standalone.py processes it only when the server is started.
```
## Metadata Imported from Tigris (Issue 445)
- **Creation Date**: 2010-01-07 07:24:54
- **Reporter**: cmpilato
- **Subcomponent**: bin
- **Version**: 1.1.3
- **Milestone**: _unscheduled_
- **Keywords**: 
- **Cc**: 
### 2010-01-07 07:28:53 by cmpilato

```
WORKAROUND:  If the site doesn't use per-root options in its configuration,
comment out this function call from lib/viewvc.py:Request.run_viewvc() (around
line 234):

       cfg.overlay_root_options(self.rootname)

No workaround exists for sites which *do* employ per-root configuration options.
```
### 2010-01-07 08:06:43 by cmpilato

```
I've committed a fix to trunk (and backported to 1.1.x) which causes the
per-root configuration accounting only to kick in when real per-root options
have been detected and applied.  This should make standalone.py work as expected
for everyone who is not using per-root configuration options.  I imagine that
that's most folks.  I'll leave this issue open, though, to track the full
resolution of the underlying problem:  that ViewVC's standalone.py wants to read
the configuration once and apply it to multiple requests, but ViewVC's core
libraries want to treat the configuration as new per-request.
```
### 2010-01-07 08:12:23 by cmpilato

```
Here's a patch against 1.1.x that folks can use in the meantime:

http://viewvc.tigris.org/source/browse/viewvc/branches/1.1.x/lib/config.py?view=patch&r1=2316&r2=2317&pathrev=2317
```

**Comment by futatuki** [comment]
This was fixed by merging PR #300, which was also needed for getting #299 fully work on standalone server.  Let's update CHANGES file after PR #259 would be merged.
